package cmc.com.ktnb.entity.TTKT.ket_thuc_ttkt;

import java.util.Date;

import cmc.com.ktnb.pl.hb.entity.PersistentObject;

/**
 * TtktKtBcKqThucHienKl generated by MyEclipse Persistence Tools
 */

public class TtktKtBcKqThucHienKL extends PersistentObject implements java.io.Serializable {

	// Fields

	private String id;

	private String idCuocTtkt;

	private Long soDviDuocTtkt;

	private Long soDviSaiPham;

	private Double tienPhaiThuCongChucThue;

	private Double tienHoanTraCongChucThue;

	private Double tienPhaiThuNguoiNopThue;

	private Double tienHoanTraNguoiNopThue;

	private Long soKiemDiem;

	private Long soHaBacLuong;

	private Long soKhienTrach;

	private Long soThoiViec;

	private Long soCanhCao;

	private Long soSdbsVbpq;

	private Long soSdbsQtqc;

	private Long soTtktThue;

	private Double tienPhaiThuTtktThue;

	private Double tienHoanTraTtktThue;

	private Long kienNghiKhac;

	private Date ngayNhanBckq;

	private String idNguoiCapNhat;

	private String tenNguoiCapNhap;

	private Date ngayCapNhat;

	private Double soTienThuHtraSpKhac;

	private Long soGiangChuc;

	private Long soCachChuc;

	private Long soKhac;

	private Long soXlhsCoAn;

	private Long ketThucTdoiThanh;

	// Constructors

	/** default constructor */
	public TtktKtBcKqThucHienKL() {
	}

	/** minimal constructor */
	public TtktKtBcKqThucHienKL(String id) {
		this.id = id;

	}

	/** full constructor */
	public TtktKtBcKqThucHienKL(String id, String idCuocTtkt,
			Long soDviDuocTtkt, Long soDviSaiPham,
			Double tienPhaiThuCongChucThue, Double tienHoanTraCongChucThue,
			Double tienPhaiThuNguoiNopThue, Double tienHoanTraNguoiNopThue,
			Long soKiemDiem, Long soHaBacLuong, Long soKhienTrach,
			Long soThoiViec, Long soCanhCao, Long soSdbsVbpq, Long soSdbsQtqc,
			Long soTtktThue, Double tienPhaiThuTtktThue,
			Double tienHoanTraTtktThue, Long kienNghiKhac, Date ngayNhanBckq,
			String idNguoiCapNhat, String tenNguoiCapNhap, Date ngayCapNhat,
			Double soTienThuHtraSpKhac, Long soGiangChuc, Long soCachChuc,
			Long soKhac, Long soXlhsCoAn, Long ketThucTdoiThanh) {
		this.id = id;
		this.idCuocTtkt = idCuocTtkt;
		this.soDviDuocTtkt = soDviDuocTtkt;
		this.soDviSaiPham = soDviSaiPham;
		this.tienPhaiThuCongChucThue = tienPhaiThuCongChucThue;
		this.tienHoanTraCongChucThue = tienHoanTraCongChucThue;
		this.tienPhaiThuNguoiNopThue = tienPhaiThuNguoiNopThue;
		this.tienHoanTraNguoiNopThue = tienHoanTraNguoiNopThue;
		this.soKiemDiem = soKiemDiem;
		this.soHaBacLuong = soHaBacLuong;
		this.soKhienTrach = soKhienTrach;
		this.soThoiViec = soThoiViec;
		this.soCanhCao = soCanhCao;
		this.soSdbsVbpq = soSdbsVbpq;
		this.soSdbsQtqc = soSdbsQtqc;
		this.soTtktThue = soTtktThue;
		this.tienPhaiThuTtktThue = tienPhaiThuTtktThue;
		this.tienHoanTraTtktThue = tienHoanTraTtktThue;
		this.kienNghiKhac = kienNghiKhac;
		this.ngayNhanBckq = ngayNhanBckq;
		this.idNguoiCapNhat = idNguoiCapNhat;
		this.tenNguoiCapNhap = tenNguoiCapNhap;
		this.ngayCapNhat = ngayCapNhat;
		this.soTienThuHtraSpKhac = soTienThuHtraSpKhac;
		this.soGiangChuc = soGiangChuc;
		this.soCachChuc = soCachChuc;
		this.soKhac = soKhac;
		this.soXlhsCoAn = soXlhsCoAn;
		this.ketThucTdoiThanh = ketThucTdoiThanh;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getIdCuocTtkt() {
		return idCuocTtkt;
	}

	public void setIdCuocTtkt(String idCuocTtkt) {
		this.idCuocTtkt = idCuocTtkt;
	}

	public Long getSoDviDuocTtkt() {
		return this.soDviDuocTtkt;
	}

	public void setSoDviDuocTtkt(Long soDviDuocTtkt) {
		this.soDviDuocTtkt = soDviDuocTtkt;
	}

	public Long getSoDviSaiPham() {
		return this.soDviSaiPham;
	}

	public void setSoDviSaiPham(Long soDviSaiPham) {
		this.soDviSaiPham = soDviSaiPham;
	}

	public Double getTienPhaiThuCongChucThue() {
		return this.tienPhaiThuCongChucThue;
	}

	public void setTienPhaiThuCongChucThue(Double tienPhaiThuCongChucThue) {
		this.tienPhaiThuCongChucThue = tienPhaiThuCongChucThue;
	}

	public Double getTienHoanTraCongChucThue() {
		return this.tienHoanTraCongChucThue;
	}

	public void setTienHoanTraCongChucThue(Double tienHoanTraCongChucThue) {
		this.tienHoanTraCongChucThue = tienHoanTraCongChucThue;
	}

	public Double getTienPhaiThuNguoiNopThue() {
		return this.tienPhaiThuNguoiNopThue;
	}

	public void setTienPhaiThuNguoiNopThue(Double tienPhaiThuNguoiNopThue) {
		this.tienPhaiThuNguoiNopThue = tienPhaiThuNguoiNopThue;
	}

	public Double getTienHoanTraNguoiNopThue() {
		return this.tienHoanTraNguoiNopThue;
	}

	public void setTienHoanTraNguoiNopThue(Double tienHoanTraNguoiNopThue) {
		this.tienHoanTraNguoiNopThue = tienHoanTraNguoiNopThue;
	}

	public Long getSoKiemDiem() {
		return this.soKiemDiem;
	}

	public void setSoKiemDiem(Long soKiemDiem) {
		this.soKiemDiem = soKiemDiem;
	}

	public Long getSoHaBacLuong() {
		return this.soHaBacLuong;
	}

	public void setSoHaBacLuong(Long soHaBacLuong) {
		this.soHaBacLuong = soHaBacLuong;
	}

	public Long getSoKhienTrach() {
		return this.soKhienTrach;
	}

	public void setSoKhienTrach(Long soKhienTrach) {
		this.soKhienTrach = soKhienTrach;
	}

	public Long getSoThoiViec() {
		return this.soThoiViec;
	}

	public void setSoThoiViec(Long soThoiViec) {
		this.soThoiViec = soThoiViec;
	}

	public Long getSoCanhCao() {
		return this.soCanhCao;
	}

	public void setSoCanhCao(Long soCanhCao) {
		this.soCanhCao = soCanhCao;
	}

	public Long getSoSdbsVbpq() {
		return this.soSdbsVbpq;
	}

	public void setSoSdbsVbpq(Long soSdbsVbpq) {
		this.soSdbsVbpq = soSdbsVbpq;
	}

	public Long getSoSdbsQtqc() {
		return this.soSdbsQtqc;
	}

	public void setSoSdbsQtqc(Long soSdbsQtqc) {
		this.soSdbsQtqc = soSdbsQtqc;
	}

	public Long getSoTtktThue() {
		return this.soTtktThue;
	}

	public void setSoTtktThue(Long soTtktThue) {
		this.soTtktThue = soTtktThue;
	}

	public Double getTienPhaiThuTtktThue() {
		return this.tienPhaiThuTtktThue;
	}

	public void setTienPhaiThuTtktThue(Double tienPhaiThuTtktThue) {
		this.tienPhaiThuTtktThue = tienPhaiThuTtktThue;
	}

	public Double getTienHoanTraTtktThue() {
		return this.tienHoanTraTtktThue;
	}

	public void setTienHoanTraTtktThue(Double tienHoanTraTtktThue) {
		this.tienHoanTraTtktThue = tienHoanTraTtktThue;
	}

	public Long getKienNghiKhac() {
		return this.kienNghiKhac;
	}

	public void setKienNghiKhac(Long kienNghiKhac) {
		this.kienNghiKhac = kienNghiKhac;
	}

	public Date getNgayNhanBckq() {
		return this.ngayNhanBckq;
	}

	public void setNgayNhanBckq(Date ngayNhanBckq) {
		this.ngayNhanBckq = ngayNhanBckq;
	}

	public String getIdNguoiCapNhat() {
		return this.idNguoiCapNhat;
	}

	public void setIdNguoiCapNhat(String idNguoiCapNhat) {
		this.idNguoiCapNhat = idNguoiCapNhat;
	}

	public String getTenNguoiCapNhap() {
		return this.tenNguoiCapNhap;
	}

	public void setTenNguoiCapNhap(String tenNguoiCapNhap) {
		this.tenNguoiCapNhap = tenNguoiCapNhap;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	public Double getSoTienThuHtraSpKhac() {
		return this.soTienThuHtraSpKhac;
	}

	public void setSoTienThuHtraSpKhac(Double soTienThuHtraSpKhac) {
		this.soTienThuHtraSpKhac = soTienThuHtraSpKhac;
	}

	public Long getSoGiangChuc() {
		return this.soGiangChuc;
	}

	public void setSoGiangChuc(Long soGiangChuc) {
		this.soGiangChuc = soGiangChuc;
	}

	public Long getSoCachChuc() {
		return this.soCachChuc;
	}

	public void setSoCachChuc(Long soCachChuc) {
		this.soCachChuc = soCachChuc;
	}

	public Long getSoKhac() {
		return this.soKhac;
	}

	public void setSoKhac(Long soKhac) {
		this.soKhac = soKhac;
	}

	public Long getSoXlhsCoAn() {
		return this.soXlhsCoAn;
	}

	public void setSoXlhsCoAn(Long soXlhsCoAn) {
		this.soXlhsCoAn = soXlhsCoAn;
	}

	public Long getKetThucTdoiThanh() {
		return this.ketThucTdoiThanh;
	}

	public void setKetThucTdoiThanh(Long ketThucTdoiThanh) {
		this.ketThucTdoiThanh = ketThucTdoiThanh;
	}

}