package cmc.com.ktnb.pl.hb.entity;

import java.util.Date;

/**
 * KntcQdinhXm generated by MyEclipse Persistence Tools
 */

public class KntcQdinhXm extends cmc.com.ktnb.pl.hb.entity.PersistentObject
		implements java.io.Serializable {

	// Fields
	private String ma; 
	private String maQd;

	private String diaDiem;

	private String canCuPly;

	private String benLienQuan;

	private Date ngayTrinhKy;

	private Date ngayKy;

	private String YKienTrinh;

	private Date ngayTrinhDuyet;

	private Date ngayDuyet;

	private String YKienDuyet;

	private Date ngayCapNhat;

	private String nguoiCapNhat;

	private String maHs;

	private Date ngayLap;

	private String mucDich;

	private String bangChung;

	private String phuongTien;

	private Long trangThai;

	private String soVanBan;

	private Long soNgayXm;

	private String noiDungXm;

	private String benLienQuanTt;

	private String nguoiBiKntcMa;

	private String nguoiBiKntcTen;

	private String nguoiBiKntcHanhVi;

	private Date tuNgayXm;

	private Date denNgayXm;

	private String canCuNvu;

	private String deNghiTruongBoPhan;
	private String chucDanhCanBoTqXm;

	// Constructors

	/** default constructor */
	public KntcQdinhXm() {
	}

	/** minimal constructor */
	public KntcQdinhXm(String maQd, String maHs) {
		this.maQd = maQd;
		this.maHs = maHs;
	}

	/** full constructor */
	public KntcQdinhXm(String maQd, String diaDiem, String canCuPly,
			String benLienQuan, Date ngayTrinhKy, Date ngayKy,
			String YKienTrinh, Date ngayTrinhDuyet, Date ngayDuyet,
			String YKienDuyet, Date ngayCapNhat, String nguoiCapNhat,
			String maHs, Date ngayLap, String mucDich, String bangChung,
			String phuongTien, Long trangThai, String soVanBan, Long soNgayXm,
			String noiDungXm, String benLienQuanTt, String nguoiBiTcMa,
			String nguoiBiTcTen, String nguoiBiTcHanhVi, Date tuNgayXm,
			Date denNgayXm, String canCuNvu, String deNghiTruongBoPhan, String chucDanhCanBoTqXm) {
		this.maQd = maQd;
		this.diaDiem = diaDiem;
		this.canCuPly = canCuPly;
		this.benLienQuan = benLienQuan;
		this.ngayTrinhKy = ngayTrinhKy;
		this.ngayKy = ngayKy;
		this.YKienTrinh = YKienTrinh;
		this.ngayTrinhDuyet = ngayTrinhDuyet;
		this.ngayDuyet = ngayDuyet;
		this.YKienDuyet = YKienDuyet;
		this.ngayCapNhat = ngayCapNhat;
		this.nguoiCapNhat = nguoiCapNhat;
		this.maHs = maHs;
		this.ngayLap = ngayLap;
		this.mucDich = mucDich;
		this.bangChung = bangChung;
		this.phuongTien = phuongTien;
		this.trangThai = trangThai;
		this.soVanBan = soVanBan;
		this.soNgayXm = soNgayXm;
		this.noiDungXm = noiDungXm;
		this.benLienQuanTt = benLienQuanTt;
		this.nguoiBiKntcMa = nguoiBiTcMa;
		this.nguoiBiKntcTen = nguoiBiTcTen;
		this.nguoiBiKntcHanhVi = nguoiBiTcHanhVi;
		this.tuNgayXm = tuNgayXm;
		this.denNgayXm = denNgayXm;
		this.canCuNvu = canCuNvu;
		this.deNghiTruongBoPhan = deNghiTruongBoPhan;
	}

	// Property accessors

	public String getMaQd() {
		return this.maQd;
	}

	public void setMaQd(String maQd) {
		this.maQd = maQd;
	}

	public String getDiaDiem() {
		return this.diaDiem;
	}

	public void setDiaDiem(String diaDiem) {
		this.diaDiem = diaDiem;
	}

	public String getCanCuPly() {
		return this.canCuPly;
	}

	public void setCanCuPly(String canCuPly) {
		this.canCuPly = canCuPly;
	}

	public String getBenLienQuan() {
		return this.benLienQuan;
	}

	public void setBenLienQuan(String benLienQuan) {
		this.benLienQuan = benLienQuan;
	}

	public Date getNgayTrinhKy() {
		return this.ngayTrinhKy;
	}

	public void setNgayTrinhKy(Date ngayTrinhKy) {
		this.ngayTrinhKy = ngayTrinhKy;
	}

	public Date getNgayKy() {
		return this.ngayKy;
	}

	public void setNgayKy(Date ngayKy) {
		this.ngayKy = ngayKy;
	}

	public String getYKienTrinh() {
		return this.YKienTrinh;
	}

	public void setYKienTrinh(String YKienTrinh) {
		this.YKienTrinh = YKienTrinh;
	}

	public Date getNgayTrinhDuyet() {
		return this.ngayTrinhDuyet;
	}

	public void setNgayTrinhDuyet(Date ngayTrinhDuyet) {
		this.ngayTrinhDuyet = ngayTrinhDuyet;
	}

	public Date getNgayDuyet() {
		return this.ngayDuyet;
	}

	public void setNgayDuyet(Date ngayDuyet) {
		this.ngayDuyet = ngayDuyet;
	}

	public String getYKienDuyet() {
		return this.YKienDuyet;
	}

	public void setYKienDuyet(String YKienDuyet) {
		this.YKienDuyet = YKienDuyet;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	public String getNguoiCapNhat() {
		return this.nguoiCapNhat;
	}

	public void setNguoiCapNhat(String nguoiCapNhat) {
		this.nguoiCapNhat = nguoiCapNhat;
	}

	public String getMaHs() {
		return this.maHs;
	}

	public void setMaHs(String maHs) {
		this.maHs = maHs;
	}

	public Date getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(Date ngayLap) {
		this.ngayLap = ngayLap;
	}

	public String getMucDich() {
		return this.mucDich;
	}

	public void setMucDich(String mucDich) {
		this.mucDich = mucDich;
	}

	public String getBangChung() {
		return this.bangChung;
	}

	public void setBangChung(String bangChung) {
		this.bangChung = bangChung;
	}

	public String getPhuongTien() {
		return this.phuongTien;
	}

	public void setPhuongTien(String phuongTien) {
		this.phuongTien = phuongTien;
	}

	public Long getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Long trangThai) {
		this.trangThai = trangThai;
	}

	public String getSoVanBan() {
		return this.soVanBan;
	}

	public void setSoVanBan(String soVanBan) {
		this.soVanBan = soVanBan;
	}

	public Long getSoNgayXm() {
		return this.soNgayXm;
	}

	public void setSoNgayXm(Long soNgayXm) {
		this.soNgayXm = soNgayXm;
	}

	public String getNoiDungXm() {
		return this.noiDungXm;
	}

	public void setNoiDungXm(String noiDungXm) {
		this.noiDungXm = noiDungXm;
	}

	public String getBenLienQuanTt() {
		return this.benLienQuanTt;
	}

	public void setBenLienQuanTt(String benLienQuanTt) {
		this.benLienQuanTt = benLienQuanTt;
	}

	public String getNguoiBiKntcMa() {
		return this.nguoiBiKntcMa;
	}

	public void setNguoiBiKntcMa(String nguoiBiTcMa) {
		this.nguoiBiKntcMa = nguoiBiTcMa;
	}

	public String getNguoiBiKntcTen() {
		return this.nguoiBiKntcTen;
	}

	public void setNguoiBiKntcTen(String nguoiBiTcTen) {
		this.nguoiBiKntcTen = nguoiBiTcTen;
	}

	public String getNguoiBiKntcHanhVi() {
		return this.nguoiBiKntcHanhVi;
	}

	public void setNguoiBiKntcHanhVi(String nguoiBiTcHanhVi) {
		this.nguoiBiKntcHanhVi = nguoiBiTcHanhVi;
	}

	public Date getTuNgayXm() {
		return this.tuNgayXm;
	}

	public void setTuNgayXm(Date tuNgayXm) {
		this.tuNgayXm = tuNgayXm;
	}

	public Date getDenNgayXm() {
		return this.denNgayXm;
	}

	public void setDenNgayXm(Date denNgayXm) {
		this.denNgayXm = denNgayXm;
	}

	public String getCanCuNvu() {
		return this.canCuNvu;
	}

	public void setCanCuNvu(String canCuNvu) {
		this.canCuNvu = canCuNvu;
	}

	public String getDeNghiTruongBoPhan() {
		return this.deNghiTruongBoPhan;
	}

	public void setDeNghiTruongBoPhan(String deNghiTruongBoPhan) {
		this.deNghiTruongBoPhan = deNghiTruongBoPhan;
	}

	public String getMa() {
		return ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}

	public String getChucDanhCanBoTqXm() {
		return this.chucDanhCanBoTqXm;
	}

	public void setChucDanhCanBoTqXm (String chucDanhCanBoTqXm) {
		this.chucDanhCanBoTqXm = chucDanhCanBoTqXm;
	}

}