package cmc.com.ktnb.pl.hb.entity;

import java.util.Date;

/**
 * KntcKqxmKluatKnghi generated by MyEclipse Persistence Tools
 */

public class KntcKqxmKluatKnghi extends cmc.com.ktnb.pl.hb.entity.PersistentObject implements java.io.Serializable {

	// Fields
	public static final String LOAI_BC_KQ_XM_TC ="23/KNTC";
	public static final String LOAI_KET_LUAN_TC ="24/KNTC";
	
	private String ma,soKl;
	private Long xlyHinhThuc;

	private Date ngayTrinhKy;

	private Date ngayKy;

	private String YKienTrinh;

	private Date ngayTrinhDuyet;

	private Date ngayDuyet;

	private String YKienDuyet;

	private Date ngayCapNhat;

	private String nguoiCapNhat;

	private String maQd,maHs;

	private Long xlySoNguoi;

	private String xlyGiaiPhap;

	private Double knthNnSoTien;

	private String knthNnLoai;

	private Double knthNnTriGia;

	private Double knthNnDat;

	private Double htcdTien;

	private String htcdLoai;

	private Double htcdTriGia;

	private Double htcdDat;

	private Long tinhTrang;

	private String loaiKq;

	private String diaDiem;

	private Date ngayLap;

	private String noiDungKn;

	private String quyetDinhHc;

	private String ketQuaXm;

	private String kienNghi;

	private String maCqt;

	private Long denBuSoNguoi;

	private String lyDoNtc;

	private String YKienKhacTrongDoan;

	private String YKienTdTtcqt;

	private String ketQuaXmTc;

	private String kienNghiTcKhac;
	
	private String donViDuocGuiKl;
	
	private String loaiKl,noiDungToCao;
	
	private Date tuNgayGq,denNgayGq;

	// Constructors

	/** default constructor */
	public KntcKqxmKluatKnghi() {
	}

	/** minimal constructor */
	public KntcKqxmKluatKnghi(String ma, String maQd, String diaDiem, Date ngayLap, String maCqt) {
		this.ma = ma;
		this.maQd = maQd;
		this.diaDiem = diaDiem;
		this.ngayLap = ngayLap;
		this.maCqt = maCqt;
	}

	/** full constructor */
	public KntcKqxmKluatKnghi(
		String ma,
		String noiDungMa,
		String noiDungTen,
		Long xlyHinhThuc,
		Date ngayTrinhKy,
		Date ngayKy,
		String YKienTrinh,
		Date ngayTrinhDuyet,
		Date ngayDuyet,
		String YKienDuyet,
		Date ngayCapNhat,
		String nguoiCapNhat,
		String maQd,
		Long xlySoNguoi,
		String xlyGiaiPhap,
		Double knthNnSoTien,
		String knthNnLoai,
		Double knthNnTriGia,
		Double knthNnDat,
		Double htcdTien,
		String htcdLoai,
		Double htcdTriGia,
		Double htcdDat,
		Long tinhTrang,
		String loaiKq,
		String diaDiem,
		Date ngayLap,
		String noiDungKn,
		String quyetDinhHc,
		String ketQuaXm,
		String kienNghi,
		String maCqt,
		Long denBuSoNguoi,
		String lyDoNtc,
		String YKienKhacTrongDoan,
		String YKienTdTtcqt,
		String ketQuaXmTc,
		String kienNghiTcKhac) {
		this.ma = ma;
		this.xlyHinhThuc = xlyHinhThuc;
		this.ngayTrinhKy = ngayTrinhKy;
		this.ngayKy = ngayKy;
		this.YKienTrinh = YKienTrinh;
		this.ngayTrinhDuyet = ngayTrinhDuyet;
		this.ngayDuyet = ngayDuyet;
		this.YKienDuyet = YKienDuyet;
		this.ngayCapNhat = ngayCapNhat;
		this.nguoiCapNhat = nguoiCapNhat;
		this.maQd = maQd;
		this.xlySoNguoi = xlySoNguoi;
		this.xlyGiaiPhap = xlyGiaiPhap;
		this.knthNnSoTien = knthNnSoTien;
		this.knthNnLoai = knthNnLoai;
		this.knthNnTriGia = knthNnTriGia;
		this.knthNnDat = knthNnDat;
		this.htcdTien = htcdTien;
		this.htcdLoai = htcdLoai;
		this.htcdTriGia = htcdTriGia;
		this.htcdDat = htcdDat;
		this.tinhTrang = tinhTrang;
		this.loaiKq = loaiKq;
		this.diaDiem = diaDiem;
		this.ngayLap = ngayLap;
		this.noiDungKn = noiDungKn;
		this.quyetDinhHc = quyetDinhHc;
		this.ketQuaXm = ketQuaXm;
		this.kienNghi = kienNghi;
		this.maCqt = maCqt;
		this.denBuSoNguoi = denBuSoNguoi;
		this.lyDoNtc = lyDoNtc;
		this.YKienKhacTrongDoan = YKienKhacTrongDoan;
		this.YKienTdTtcqt = YKienTdTtcqt;
		this.ketQuaXmTc = ketQuaXmTc;
		this.kienNghiTcKhac = kienNghiTcKhac;
	}

	// Property accessors

	public String getMa() {
		return this.ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}
	public Long getXlyHinhThuc() {
		return this.xlyHinhThuc;
	}

	public void setXlyHinhThuc(Long xlyHinhThuc) {
		this.xlyHinhThuc = xlyHinhThuc;
	}

	public Date getNgayTrinhKy() {
		return this.ngayTrinhKy;
	}

	public void setNgayTrinhKy(Date ngayTrinhKy) {
		this.ngayTrinhKy = ngayTrinhKy;
	}

	public Date getNgayKy() {
		return this.ngayKy;
	}

	public void setNgayKy(Date ngayKy) {
		this.ngayKy = ngayKy;
	}

	public String getYKienTrinh() {
		return this.YKienTrinh;
	}

	public void setYKienTrinh(String YKienTrinh) {
		this.YKienTrinh = YKienTrinh;
	}

	public Date getNgayTrinhDuyet() {
		return this.ngayTrinhDuyet;
	}

	public void setNgayTrinhDuyet(Date ngayTrinhDuyet) {
		this.ngayTrinhDuyet = ngayTrinhDuyet;
	}

	public Date getNgayDuyet() {
		return this.ngayDuyet;
	}

	public void setNgayDuyet(Date ngayDuyet) {
		this.ngayDuyet = ngayDuyet;
	}

	public String getYKienDuyet() {
		return this.YKienDuyet;
	}

	public void setYKienDuyet(String YKienDuyet) {
		this.YKienDuyet = YKienDuyet;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	public String getNguoiCapNhat() {
		return this.nguoiCapNhat;
	}

	public void setNguoiCapNhat(String nguoiCapNhat) {
		this.nguoiCapNhat = nguoiCapNhat;
	}

	public String getMaQd() {
		return this.maQd;
	}

	public void setMaQd(String maQd) {
		this.maQd = maQd;
	}

	public Long getXlySoNguoi() {
		return this.xlySoNguoi;
	}

	public void setXlySoNguoi(Long xlySoNguoi) {
		this.xlySoNguoi = xlySoNguoi;
	}

	public String getXlyGiaiPhap() {
		return this.xlyGiaiPhap;
	}

	public void setXlyGiaiPhap(String xlyGiaiPhap) {
		this.xlyGiaiPhap = xlyGiaiPhap;
	}

	public Double getKnthNnSoTien() {
		return this.knthNnSoTien;
	}

	public void setKnthNnSoTien(Double knthNnSoTien) {
		this.knthNnSoTien = knthNnSoTien;
	}

	public String getKnthNnLoai() {
		return this.knthNnLoai;
	}

	public void setKnthNnLoai(String knthNnLoai) {
		this.knthNnLoai = knthNnLoai;
	}

	public Double getKnthNnTriGia() {
		return this.knthNnTriGia;
	}

	public void setKnthNnTriGia(Double knthNnTriGia) {
		this.knthNnTriGia = knthNnTriGia;
	}

	public Double getKnthNnDat() {
		return this.knthNnDat;
	}

	public void setKnthNnDat(Double knthNnDat) {
		this.knthNnDat = knthNnDat;
	}

	public Double getHtcdTien() {
		return this.htcdTien;
	}

	public void setHtcdTien(Double htcdTien) {
		this.htcdTien = htcdTien;
	}

	public String getHtcdLoai() {
		return this.htcdLoai;
	}

	public void setHtcdLoai(String htcdLoai) {
		this.htcdLoai = htcdLoai;
	}

	public Double getHtcdTriGia() {
		return this.htcdTriGia;
	}

	public void setHtcdTriGia(Double htcdTriGia) {
		this.htcdTriGia = htcdTriGia;
	}

	public Double getHtcdDat() {
		return this.htcdDat;
	}

	public void setHtcdDat(Double htcdDat) {
		this.htcdDat = htcdDat;
	}

	public Long getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(Long tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	public String getLoaiKq() {
		return this.loaiKq;
	}

	public void setLoaiKq(String loaiKq) {
		this.loaiKq = loaiKq;
	}

	public String getDiaDiem() {
		return this.diaDiem;
	}

	public void setDiaDiem(String diaDiem) {
		this.diaDiem = diaDiem;
	}

	public Date getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(Date ngayLap) {
		this.ngayLap = ngayLap;
	}

	public String getNoiDungKn() {
		return this.noiDungKn;
	}

	public void setNoiDungKn(String noiDungKn) {
		this.noiDungKn = noiDungKn;
	}

	public String getQuyetDinhHc() {
		return this.quyetDinhHc;
	}

	public void setQuyetDinhHc(String quyetDinhHc) {
		this.quyetDinhHc = quyetDinhHc;
	}

	public String getKetQuaXm() {
		return this.ketQuaXm;
	}

	public void setKetQuaXm(String ketQuaXm) {
		this.ketQuaXm = ketQuaXm;
	}

	public String getKienNghi() {
		return this.kienNghi;
	}

	public void setKienNghi(String kienNghi) {
		this.kienNghi = kienNghi;
	}

	public String getMaCqt() {
		return this.maCqt;
	}

	public void setMaCqt(String maCqt) {
		this.maCqt = maCqt;
	}

	public Long getDenBuSoNguoi() {
		return this.denBuSoNguoi;
	}

	public void setDenBuSoNguoi(Long denBuSoNguoi) {
		this.denBuSoNguoi = denBuSoNguoi;
	}

	public String getLyDoNtc() {
		return this.lyDoNtc;
	}

	public void setLyDoNtc(String lyDoNtc) {
		this.lyDoNtc = lyDoNtc;
	}

	public String getYKienKhacTrongDoan() {
		return this.YKienKhacTrongDoan;
	}

	public void setYKienKhacTrongDoan(String YKienKhacTrongDoan) {
		this.YKienKhacTrongDoan = YKienKhacTrongDoan;
	}

	public String getYKienTdTtcqt() {
		return this.YKienTdTtcqt;
	}

	public void setYKienTdTtcqt(String YKienTdTtcqt) {
		this.YKienTdTtcqt = YKienTdTtcqt;
	}

	public String getKetQuaXmTc() {
		return this.ketQuaXmTc;
	}

	public void setKetQuaXmTc(String ketQuaXmTc) {
		this.ketQuaXmTc = ketQuaXmTc;
	}

	public String getKienNghiTcKhac() {
		return this.kienNghiTcKhac;
	}

	public void setKienNghiTcKhac(String kienNghiTcKhac) {
		this.kienNghiTcKhac = kienNghiTcKhac;
	}

	/**
	 * @return
	 */
	public String getDonViDuocGuiKl() {
		return donViDuocGuiKl;
	}

	/**
	 * @param string
	 */
	public void setDonViDuocGuiKl(String string) {
		donViDuocGuiKl = string;
	}

	/**
	 * @return
	 */
	public String getLoaiKl() {
		return loaiKl;
	}

	/**
	 * @param string
	 */
	public void setLoaiKl(String string) {
		loaiKl = string;
	}

	public String getMaHs() {
		return maHs;
	}

	public void setMaHs(String maHs) {
		this.maHs = maHs;
	}

	public Date getDenNgayGq() {
		return denNgayGq;
	}

	public void setDenNgayGq(Date denNgayGq) {
		this.denNgayGq = denNgayGq;
	}

	public Date getTuNgayGq() {
		return tuNgayGq;
	}

	public void setTuNgayGq(Date tuNgayGq) {
		this.tuNgayGq = tuNgayGq;
	}

	public String getSoKl() {
		return soKl;
	}

	public void setSoKl(String soKl) {
		this.soKl = soKl;
	}

	public String getNoiDungToCao() {
		return noiDungToCao;
	}

	public void setNoiDungToCao(String noiDungToCao) {
		this.noiDungToCao = noiDungToCao;
	}

}