package cmc.com.ktnb.pl.hb.entity;

/**
 * KntcCanBoRlsId generated by MyEclipse Persistence Tools
 */

public class KntcCanBoRlsId extends cmc.com.ktnb.pl.hb.entity.PersistentObject
		implements java.io.Serializable {

	// Fields

	private String maCanbo;

	private String maHs;

	private Long lanTd;

	private String loaiCb;

	// Constructors

	/** default constructor */
	public KntcCanBoRlsId() {
	}

	/** full constructor */
	public KntcCanBoRlsId(String maCanbo, String maHs, Long lanTd, String loaiCb) {
		this.maCanbo = maCanbo;
		this.maHs = maHs;
		this.lanTd = lanTd;
		this.loaiCb = loaiCb;
	}

	// Property accessors

	public String getMaCanbo() {
		return this.maCanbo;
	}

	public void setMaCanbo(String maCanbo) {
		this.maCanbo = maCanbo;
	}

	public String getMaHs() {
		return this.maHs;
	}

	public void setMaHs(String maHs) {
		this.maHs = maHs;
	}

	public Long getLanTd() {
		return this.lanTd;
	}

	public void setLanTd(Long lanTd) {
		this.lanTd = lanTd;
	}

	public String getLoaiCb() {
		return this.loaiCb;
	}

	public void setLoaiCb(String loaiCb) {
		this.loaiCb = loaiCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KntcCanBoRlsId))
			return false;
		KntcCanBoRlsId castOther = (KntcCanBoRlsId) other;

		return ((this.getMaCanbo() == castOther.getMaCanbo()) || (this
				.getMaCanbo() != null
				&& castOther.getMaCanbo() != null && this.getMaCanbo().equals(
				castOther.getMaCanbo())))
				&& ((this.getMaHs() == castOther.getMaHs()) || (this.getMaHs() != null
						&& castOther.getMaHs() != null && this.getMaHs()
						.equals(castOther.getMaHs())))
				&& ((this.getLanTd() == castOther.getLanTd()) || (this
						.getLanTd() != null
						&& castOther.getLanTd() != null && this.getLanTd()
						.equals(castOther.getLanTd())))
				&& ((this.getLoaiCb() == castOther.getLoaiCb()) || (this
						.getLoaiCb() != null
						&& castOther.getLoaiCb() != null && this.getLoaiCb()
						.equals(castOther.getLoaiCb())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMaCanbo() == null ? 0 : this.getMaCanbo().hashCode());
		result = 37 * result
				+ (getMaHs() == null ? 0 : this.getMaHs().hashCode());
		result = 37 * result
				+ (getLanTd() == null ? 0 : this.getLanTd().hashCode());
		result = 37 * result
				+ (getLoaiCb() == null ? 0 : this.getLoaiCb().hashCode());
		return result;
	}

}