package cmc.com.ktnb.pl.hb.entity;

/**
 * KntcBienBanNguoiRls generated by MyEclipse Persistence Tools
 */

public class KntcBienBanNguoiRls extends
		cmc.com.ktnb.pl.hb.entity.PersistentObject implements
		java.io.Serializable {

	// Fields

	private String ma;

	private String maBb;

	private String loaiBenLv;

	private String loaiBb;

	private String thanhPhan;

	// Constructors

	/** default constructor */
	public KntcBienBanNguoiRls() {
	}

	/** minimal constructor */
	public KntcBienBanNguoiRls(String ma, String maBb) {
		this.ma = ma;
		this.maBb = maBb;
	}
	// Property accessors

	public String getMa() {
		return this.ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}

	public String getMaBb() {
		return this.maBb;
	}

	public void setMaBb(String maBb) {
		this.maBb = maBb;
	}

	public String getLoaiBenLv() {
		return this.loaiBenLv;
	}

	public void setLoaiBenLv(String loaiBenLv) {
		this.loaiBenLv = loaiBenLv;
	}

	public String getLoaiBb() {
		return this.loaiBb;
	}

	public void setLoaiBb(String loaiBb) {
		this.loaiBb = loaiBb;
	}

	public String getThanhPhan() {
		return this.thanhPhan;
	}

	public void setThanhPhan(String tenNguoi) {
		this.thanhPhan = tenNguoi;
	}
}