package cmc.com.ktnb.pl.hb.entity;

import java.util.Date;

/**
 * KntcCanBoRls generated by MyEclipse Persistence Tools
 */

public class KntcCanBoRls extends cmc.com.ktnb.pl.hb.entity.PersistentObject
		implements java.io.Serializable {

	// Fields

	public static final String KNTC_CB_XU_LY = "6";

	public static final String KNTC_TVD_XAC_MINH = "5";

	private KntcCanBoRlsId id;

	private String donVi;

	private String chucVu;

	private String vaiTro;

	private Date ngayCapNhat;

	private String nguoiCapNhat;

	private Date ngayHetHluc;

	private String tenCb;
	
	// Constructors

	/** default constructor */
	public KntcCanBoRls() {
	}

	/** minimal constructor */
	public KntcCanBoRls(KntcCanBoRlsId id) {
		this.id = id;
	}

	/** full constructor */
	public KntcCanBoRls(KntcCanBoRlsId id, String donVi, String chucVu,
			String vaiTro, Date ngayCapNhat, String nguoiCapNhat,
			Date ngayHetHluc, String tenCb) {
		this.id = id;
		this.donVi = donVi;
		this.chucVu = chucVu;
		this.vaiTro = vaiTro;
		this.ngayCapNhat = ngayCapNhat;
		this.nguoiCapNhat = nguoiCapNhat;
		this.ngayHetHluc = ngayHetHluc;
		this.tenCb = tenCb;
	}

	// Property accessors

	public KntcCanBoRlsId getId() {
		return this.id;
	}

	public void setId(KntcCanBoRlsId id) {
		this.id = id;
	}

	public String getDonVi() {
		return this.donVi;
	}

	public void setDonVi(String donVi) {
		this.donVi = donVi;
	}

	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	public String getVaiTro() {
		return this.vaiTro;
	}

	public void setVaiTro(String vaiTro) {
		this.vaiTro = vaiTro;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	public String getNguoiCapNhat() {
		return this.nguoiCapNhat;
	}

	public void setNguoiCapNhat(String nguoiCapNhat) {
		this.nguoiCapNhat = nguoiCapNhat;
	}

	public Date getNgayHetHluc() {
		return this.ngayHetHluc;
	}

	public void setNgayHetHluc(Date ngayHetHluc) {
		this.ngayHetHluc = ngayHetHluc;
	}

	public String getTenCb() {
		return this.tenCb;
	}

	public void setTenCb(String tenCb) {
		this.tenCb = tenCb;
	}
}