package cmc.com.ktnb.pl.hb.entity;

import java.util.Date;

/**
 * KtnbLopTapHuan generated by MyEclipse Persistence Tools
 */

public class KtnbLopTapHuan extends cmc.com.ktnb.pl.hb.entity.PersistentObject
		implements java.io.Serializable {

	// Fields

	private String ma;

	private String tenLop;

	private String diaDiem;

	private Date ngayBatDau;

	private Date ngayKetThuc;

	private Long soNguoi;

	// Constructors

	/** default constructor */
	public KtnbLopTapHuan() {
	}

	/** minimal constructor */
	public KtnbLopTapHuan(String ma) {
		this.ma = ma;
	}

	/** full constructor */
	public KtnbLopTapHuan(String ma, String tenLop, String diaDiem,
			Date ngayBatDau, Date ngayKetThuc, Long soNguoi) {
		this.ma = ma;
		this.tenLop = tenLop;
		this.diaDiem = diaDiem;
		this.ngayBatDau = ngayBatDau;
		this.ngayKetThuc = ngayKetThuc;
		this.soNguoi = soNguoi;
	}

	// Property accessors

	public String getMa() {
		return this.ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}

	public String getTenLop() {
		return this.tenLop;
	}

	public void setTenLop(String tenLop) {
		this.tenLop = tenLop;
	}

	public String getDiaDiem() {
		return this.diaDiem;
	}

	public void setDiaDiem(String diaDiem) {
		this.diaDiem = diaDiem;
	}

	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	public Date getNgayKetThuc() {
		return this.ngayKetThuc;
	}

	public void setNgayKetThuc(Date ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}

	public Long getSoNguoi() {
		return this.soNguoi;
	}

	public void setSoNguoi(Long soNguoi) {
		this.soNguoi = soNguoi;
	}

}