package cmc.com.ktnb.pl.hb.entity;

import java.util.Date;

/**
 * KtnbVanBanChiDao generated by MyEclipse Persistence Tools
 */

public class KtnbVanBanChiDao extends
		cmc.com.ktnb.pl.hb.entity.PersistentObject implements
		java.io.Serializable {

	// Fields

	private String ma;

	private String tenVanBan;

	private String noiDung;

	private Date ngayBanHanh;

	// Constructors

	/** default constructor */
	public KtnbVanBanChiDao() {
	}

	/** minimal constructor */
	public KtnbVanBanChiDao(String ma) {
		this.ma = ma;
	}

	/** full constructor */
	public KtnbVanBanChiDao(String ma, String tenVanBan, String noiDung,
			Date ngayBanHanh) {
		this.ma = ma;
		this.tenVanBan = tenVanBan;
		this.noiDung = noiDung;
		this.ngayBanHanh = ngayBanHanh;
	}

	// Property accessors

	public String getMa() {
		return this.ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}

	public String getTenVanBan() {
		return this.tenVanBan;
	}

	public void setTenVanBan(String tenVanBan) {
		this.tenVanBan = tenVanBan;
	}

	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	public Date getNgayBanHanh() {
		return this.ngayBanHanh;
	}

	public void setNgayBanHanh(Date ngayBanHanh) {
		this.ngayBanHanh = ngayBanHanh;
	}

}