package cmc.com.ktnb.entity.TTKT.ket_thuc_ttkt;

import java.util.Date;

import cmc.com.ktnb.pl.hb.entity.PersistentObject;

/**
 * TtktKtKetLuanChuyenBC generated by MyEclipse Persistence Tools
 */

public class TtktKtKetLuanChuyenBC extends PersistentObject implements java.io.Serializable {

	// Fields

	private String id;

	private String idCuocTtkt;

	private Long soDviDuocTtkt;

	private Long soDviSaiPham;

	private Double tsTienThuCongChucThue;

	private Double tsTienTraCongChucThue;

	private Double tsTienThuNguoiNopThue;

	private Double tsTienTraNguoiNopThue;

	private Double soTienThuCongChucThue;

	private Double soTienTraCongChucThue;

	private Double soTienThuNguoiNopThue;

	private Double soTienTraNguoiNopThue;

	private Long xlhcCongVienChucThue;

	private Long xlhcDoiTuongKhac;

	private Long xlhsSoVuViec;

	private Long xlhsSoNguoi;

	private Long soSdbsVbpq;

	private Long soSdbsQtqc;

	private Long soTtktThue;

	private Long kienNghiKhac;

	private String moTa;

	private String idNguoiCapNhat;

	private String tenNguoiCapNhap;

	private Date ngayCapNhat;

	private Double tsTienThuHtraSpKhac;

	private Double soTienKnghiThuHtraSpKhac;

	private Long ktraSauTtkt;

	private Long tsKlTtktQdxlDaKtra;
	
	private Long soTienDaThuHauKiem;
	
	private Double soTienThuDoiTuongKhac;
	
	private Double soTienNopDoiTuongKhac;

	// Constructors

	/** default constructor */
	public TtktKtKetLuanChuyenBC() {
	}

	/** minimal constructor */
	public TtktKtKetLuanChuyenBC(String id) {
		this.id = id;
	}

	/** full constructor */
	public TtktKtKetLuanChuyenBC(String id, String idCuocTtkt,
			Long soDviDuocTtkt, Long soDviSaiPham,
			Double tsTienThuCongChucThue, Double tsTienTraCongChucThue,
			Double tsTienThuNguoiNopThue, Double tsTienTraNguoiNopThue,
			Double soTienThuCongChucThue, Double soTienTraCongChucThue,
			Double soTienThuNguoiNopThue, Double soTienTraNguoiNopThue,
			Long xlhcCongVienChucThue, Long xlhcDoiTuongKhac,
			Long xlhsSoVuViec, Long xlhsSoNguoi, Long soSdbsVbpq,
			Long soSdbsQtqc, Long soTtktThue, Long kienNghiKhac, String moTa,
			String idNguoiCapNhat, String tenNguoiCapNhap, Date ngayCapNhat,
			Double tsTienThuHtraSpKhac, Double soTienKnghiThuHtraSpKhac,
			Long ktraSauTtkt, Long tsKlTtktQdxlDaKtra) {
		this.id = id;
		this.idCuocTtkt = idCuocTtkt;
		this.soDviDuocTtkt = soDviDuocTtkt;
		this.soDviSaiPham = soDviSaiPham;
		this.tsTienThuCongChucThue = tsTienThuCongChucThue;
		this.tsTienTraCongChucThue = tsTienTraCongChucThue;
		this.tsTienThuNguoiNopThue = tsTienThuNguoiNopThue;
		this.tsTienTraNguoiNopThue = tsTienTraNguoiNopThue;
		this.soTienThuCongChucThue = soTienThuCongChucThue;
		this.soTienTraCongChucThue = soTienTraCongChucThue;
		this.soTienThuNguoiNopThue = soTienThuNguoiNopThue;
		this.soTienTraNguoiNopThue = soTienTraNguoiNopThue;
		this.xlhcCongVienChucThue = xlhcCongVienChucThue;
		this.xlhcDoiTuongKhac = xlhcDoiTuongKhac;
		this.xlhsSoVuViec = xlhsSoVuViec;
		this.xlhsSoNguoi = xlhsSoNguoi;
		this.soSdbsVbpq = soSdbsVbpq;
		this.soSdbsQtqc = soSdbsQtqc;
		this.soTtktThue = soTtktThue;
		this.kienNghiKhac = kienNghiKhac;
		this.moTa = moTa;
		this.idNguoiCapNhat = idNguoiCapNhat;
		this.tenNguoiCapNhap = tenNguoiCapNhap;
		this.ngayCapNhat = ngayCapNhat;
		this.tsTienThuHtraSpKhac = tsTienThuHtraSpKhac;
		this.soTienKnghiThuHtraSpKhac = soTienKnghiThuHtraSpKhac;
		this.ktraSauTtkt = ktraSauTtkt;
		this.tsKlTtktQdxlDaKtra = tsKlTtktQdxlDaKtra;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getIdCuocTtkt() {
		return idCuocTtkt;
	}

	public void setIdCuocTtkt(String idCuocTtkt) {
		this.idCuocTtkt = idCuocTtkt;
	}

	public Long getSoDviDuocTtkt() {
		return this.soDviDuocTtkt;
	}

	public void setSoDviDuocTtkt(Long soDviDuocTtkt) {
		this.soDviDuocTtkt = soDviDuocTtkt;
	}

	public Long getSoDviSaiPham() {
		return this.soDviSaiPham;
	}

	public void setSoDviSaiPham(Long soDviSaiPham) {
		this.soDviSaiPham = soDviSaiPham;
	}

	public Double getTsTienThuCongChucThue() {
		return this.tsTienThuCongChucThue;
	}

	public void setTsTienThuCongChucThue(Double tsTienThuCongChucThue) {
		this.tsTienThuCongChucThue = tsTienThuCongChucThue;
	}

	public Double getTsTienTraCongChucThue() {
		return this.tsTienTraCongChucThue;
	}

	public void setTsTienTraCongChucThue(Double tsTienTraCongChucThue) {
		this.tsTienTraCongChucThue = tsTienTraCongChucThue;
	}

	public Double getTsTienThuNguoiNopThue() {
		return this.tsTienThuNguoiNopThue;
	}

	public void setTsTienThuNguoiNopThue(Double tsTienThuNguoiNopThue) {
		this.tsTienThuNguoiNopThue = tsTienThuNguoiNopThue;
	}

	public Double getTsTienTraNguoiNopThue() {
		return this.tsTienTraNguoiNopThue;
	}

	public void setTsTienTraNguoiNopThue(Double tsTienTraNguoiNopThue) {
		this.tsTienTraNguoiNopThue = tsTienTraNguoiNopThue;
	}

	public Double getSoTienThuCongChucThue() {
		return this.soTienThuCongChucThue;
	}

	public void setSoTienThuCongChucThue(Double soTienThuCongChucThue) {
		this.soTienThuCongChucThue = soTienThuCongChucThue;
	}

	public Double getSoTienTraCongChucThue() {
		return this.soTienTraCongChucThue;
	}

	public void setSoTienTraCongChucThue(Double soTienTraCongChucThue) {
		this.soTienTraCongChucThue = soTienTraCongChucThue;
	}

	public Double getSoTienThuNguoiNopThue() {
		return this.soTienThuNguoiNopThue;
	}

	public void setSoTienThuNguoiNopThue(Double soTienThuNguoiNopThue) {
		this.soTienThuNguoiNopThue = soTienThuNguoiNopThue;
	}

	public Double getSoTienTraNguoiNopThue() {
		return this.soTienTraNguoiNopThue;
	}

	public void setSoTienTraNguoiNopThue(Double soTienTraNguoiNopThue) {
		this.soTienTraNguoiNopThue = soTienTraNguoiNopThue;
	}

	public Long getXlhcCongVienChucThue() {
		return this.xlhcCongVienChucThue;
	}

	public void setXlhcCongVienChucThue(Long xlhcCongVienChucThue) {
		this.xlhcCongVienChucThue = xlhcCongVienChucThue;
	}

	public Long getXlhcDoiTuongKhac() {
		return this.xlhcDoiTuongKhac;
	}

	public void setXlhcDoiTuongKhac(Long xlhcDoiTuongKhac) {
		this.xlhcDoiTuongKhac = xlhcDoiTuongKhac;
	}

	public Long getXlhsSoVuViec() {
		return this.xlhsSoVuViec;
	}

	public void setXlhsSoVuViec(Long xlhsSoVuViec) {
		this.xlhsSoVuViec = xlhsSoVuViec;
	}

	public Long getXlhsSoNguoi() {
		return this.xlhsSoNguoi;
	}

	public void setXlhsSoNguoi(Long xlhsSoNguoi) {
		this.xlhsSoNguoi = xlhsSoNguoi;
	}

	public Long getSoSdbsVbpq() {
		return this.soSdbsVbpq;
	}

	public void setSoSdbsVbpq(Long soSdbsVbpq) {
		this.soSdbsVbpq = soSdbsVbpq;
	}

	public Long getSoSdbsQtqc() {
		return this.soSdbsQtqc;
	}

	public void setSoSdbsQtqc(Long soSdbsQtqc) {
		this.soSdbsQtqc = soSdbsQtqc;
	}

	public Long getSoTtktThue() {
		return this.soTtktThue;
	}

	public void setSoTtktThue(Long soTtktThue) {
		this.soTtktThue = soTtktThue;
	}

	public Long getKienNghiKhac() {
		return this.kienNghiKhac;
	}

	public void setKienNghiKhac(Long kienNghiKhac) {
		this.kienNghiKhac = kienNghiKhac;
	}

	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	public String getIdNguoiCapNhat() {
		return this.idNguoiCapNhat;
	}

	public void setIdNguoiCapNhat(String idNguoiCapNhat) {
		this.idNguoiCapNhat = idNguoiCapNhat;
	}

	public String getTenNguoiCapNhap() {
		return this.tenNguoiCapNhap;
	}

	public void setTenNguoiCapNhap(String tenNguoiCapNhap) {
		this.tenNguoiCapNhap = tenNguoiCapNhap;
	}

	public Date getNgayCapNhat() {
		return this.ngayCapNhat;
	}

	public void setNgayCapNhat(Date ngayCapNhat) {
		this.ngayCapNhat = ngayCapNhat;
	}

	public Double getTsTienThuHtraSpKhac() {
		return this.tsTienThuHtraSpKhac;
	}

	public void setTsTienThuHtraSpKhac(Double tsTienThuHtraSpKhac) {
		this.tsTienThuHtraSpKhac = tsTienThuHtraSpKhac;
	}

	public Double getSoTienKnghiThuHtraSpKhac() {
		return this.soTienKnghiThuHtraSpKhac;
	}

	public void setSoTienKnghiThuHtraSpKhac(Double soTienKnghiThuHtraSpKhac) {
		this.soTienKnghiThuHtraSpKhac = soTienKnghiThuHtraSpKhac;
	}

	public Long getKtraSauTtkt() {
		return this.ktraSauTtkt;
	}

	public void setKtraSauTtkt(Long ktraSauTtkt) {
		this.ktraSauTtkt = ktraSauTtkt;
	}

	public Long getTsKlTtktQdxlDaKtra() {
		return this.tsKlTtktQdxlDaKtra;
	}

	public void setTsKlTtktQdxlDaKtra(Long tsKlTtktQdxlDaKtra) {
		this.tsKlTtktQdxlDaKtra = tsKlTtktQdxlDaKtra;
	}

	public Long getSoTienDaThuHauKiem() {
		return soTienDaThuHauKiem;
	}

	public void setSoTienDaThuHauKiem(Long soTienDaThuHauKiem) {
		this.soTienDaThuHauKiem = soTienDaThuHauKiem;
	}

	public Double getSoTienThuDoiTuongKhac() {
		return soTienThuDoiTuongKhac;
	}

	public void setSoTienThuDoiTuongKhac(Double soTienThuDoiTuongKhac) {
		this.soTienThuDoiTuongKhac = soTienThuDoiTuongKhac;
	}

	public Double getSoTienNopDoiTuongKhac() {
		return soTienNopDoiTuongKhac;
	}

	public void setSoTienNopDoiTuongKhac(Double soTienNopDoiTuongKhac) {
		this.soTienNopDoiTuongKhac = soTienNopDoiTuongKhac;
	}

}